// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (resource_id, resource_type, name, on_state, outcome)
VALUES (?, ?, ?, ?, ?)
RETURNING id, resource_id, resource_type, name, on_state, outcome, created_at
`

type InsertEventParams struct {
	ResourceID   string
	ResourceType string
	Name         string
	OnState      int64
	Outcome      string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.ResourceID,
		arg.ResourceType,
		arg.Name,
		arg.OnState,
		arg.Outcome,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.ResourceType,
		&i.Name,
		&i.OnState,
		&i.Outcome,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, resource_id, resource_type, name, on_state, outcome, created_at
FROM events
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) ListEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ResourceType,
			&i.Name,
			&i.OnState,
			&i.Outcome,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
