// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Event struct {
	ID           int64
	ResourceID   string
	ResourceType string
	Name         string
	OnState      int64
	Outcome      string
	CreatedAt    string
}

type Setting struct {
	Key   string
	Value string
}

type WatchedResource struct {
	ResourceID   string
	ResourceType string
	Name         string
	Notify       int64
}
