// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watched_resources.sql

package db

import (
	"context"
)

const deleteWatchedResource = `-- name: DeleteWatchedResource :exec
DELETE FROM watched_resources WHERE resource_id = ?
`

func (q *Queries) DeleteWatchedResource(ctx context.Context, resourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteWatchedResource, resourceID)
	return err
}

const getWatchedResource = `-- name: GetWatchedResource :one
SELECT resource_id, resource_type, name, notify FROM watched_resources WHERE resource_id = ?
`

func (q *Queries) GetWatchedResource(ctx context.Context, resourceID string) (WatchedResource, error) {
	row := q.db.QueryRowContext(ctx, getWatchedResource, resourceID)
	var i WatchedResource
	err := row.Scan(
		&i.ResourceID,
		&i.ResourceType,
		&i.Name,
		&i.Notify,
	)
	return i, err
}

const listWatchedResources = `-- name: ListWatchedResources :many
SELECT resource_id, resource_type, name, notify FROM watched_resources
`

func (q *Queries) ListWatchedResources(ctx context.Context) ([]WatchedResource, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchedResource
	for rows.Next() {
		var i WatchedResource
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceType,
			&i.Name,
			&i.Notify,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWatchedResourceNotify = `-- name: SetWatchedResourceNotify :execrows

UPDATE watched_resources SET notify = ? WHERE resource_id = ?
`

type SetWatchedResourceNotifyParams struct {
	Notify     int64
	ResourceID string
}

// notify excluded on purpose: re-watching must not un-mute
func (q *Queries) SetWatchedResourceNotify(ctx context.Context, arg SetWatchedResourceNotifyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setWatchedResourceNotify, arg.Notify, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWatchedResource = `-- name: UpsertWatchedResource :exec
INSERT INTO watched_resources (resource_id, resource_type, name)
VALUES (?, ?, ?)
ON CONFLICT (resource_id) DO UPDATE SET resource_type = excluded.resource_type, name = excluded.name
`

type UpsertWatchedResourceParams struct {
	ResourceID   string
	ResourceType string
	Name         string
}

func (q *Queries) UpsertWatchedResource(ctx context.Context, arg UpsertWatchedResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWatchedResource, arg.ResourceID, arg.ResourceType, arg.Name)
	return err
}
